name: 编译luci-app-easytier

on:
  workflow_dispatch:
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载工具链
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          wget -qO /opt/sdk.tar.zst https://mirror-03.infra.openwrt.org/releases/24.10.0-rc1/targets/x86/64/openwrt-sdk-24.10.0-rc1-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf /opt/sdk.tar.zst -C /opt
          cp -R ${{ github.workspace }} /opt/luci-app-easytier
      - name: 开始编译
        run: |
          cd /opt/openwrt-sdk*/package
          cp -R /opt/luci-app-easytier .
          cd /opt/openwrt-sdk*
          ./scripts/feeds update -a
          make defconfig
          cd /opt/openwrt-sdk*
          make package/luci-app-easytier/compile V=s -j1
          cd /opt/openwrt-sdk*/bin/packages/aarch64_generic/base
          ls
          mv *.ipk /opt/luci-app-easytier_all.ipk
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-easytier
          path: /opt/luci-app-easytier_all.ipk
     
